spring:
  application:
    name: etudiant-backend
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}

logging:
  level:
    org:
      hibernate:
        type: info
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: info
    com:
      openclassrooms:
        etudiant: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  # Injecte la clé secrète depuis la variable d'environnement JWT_SECRET du fichier .env
       secret: ${JWT_SECRET}
  # Injecte la durée d'expiration depuis la variable d'environnement JWT_EXPIRATION du fichier .env
       expiration: ${JWT_EXPIRATION}
